### ISSUE TITLE
Create Genome indices as an additional step

### ISSUE THREAD

**Issue by drpatelh** [nf-core/nanoseq#2]
The index creation process with both `Graphmap` and `minimap2` takes a few minutes for even larger genomes so its not a massive overhead. This is currently done at run-time during the alignment but there may be an option to add an additional process(es) to do this beforehand - possibly to reduce redundancy in storage? Its going to be a bit tricky because the pipeline can accept multiple genomes as input for mapping within the samplesheet. Need to figure out a way to only create the index once for any given genome and then pass this to the appropriate mapping step for that sample.

**Comment by lwratten** [comment]
Could we do this using a map? We would see if the genome is an existing key in the map and if not create index and add to the map.
i.e. `['hg19': 'path/to/minimapindex.mmi', 'grch38': 'path/to/minimapindex.mmi']`

We will also will need to do something similar for generating chromosome size files.

If this method would work would we use the same map to store all the data or different ones for different purposes? i.e. a graphmap2, minimap2, chrSizes and UCSCchrSizes with parts left empty depending on what is called:
 `genomeMap = ['hg19': ['mmi': '/path.mmi', 'gmi': 'path.gmi', 'chrSizes': 'sizes.txt', 'UCSC': 'sizes.ucsc.txt'], 'grch38': ['mmi': '/path.mmi', 'gmi': '', 'chrSizes': 'sizes.txt', 'UCSC': 'sizes.ucsc.txt']] ` 
or one for each section [indexing, chrSizes etc]?

**Comment by drpatelh** [comment]
We are using a map for the iGenomes files:
https://github.com/nf-core/nanoseq/blob/dfc374d3291134416a75f2c42d2ac49d5e12b6cb/main.nf#L181-L192

This just retrieves the `fasta` file if a particular organism key exists in `iGenomes`. The indices for `minimap2` and `graphmap` dont exist there so it would be good to start with `fasta` and then the user can provide `--index` if they have one which would just avoid creating it at run-time. This would then we staged properly via channels.

I think we will just need to also add an additional process to generate the sizes file but that should be quite easy.

Why do we need `chrSizes` and `UCSCchrSizes`? They should be the same no?

**Comment by lwratten** [comment]
The indices for `minimap` and `graphmap` rely on the flags used for the subsequent alignment call which depends on the type of data (`directRNA`, `cDNA`, `DNA` etc). So I don't think we can store with `iGenomes`. Likewise don't know if it's safe for the user to input via samplesheet or `--index` because they would have to input the exact command line flags for the indexing as what will be used for the alignment. 

Do think it's important to only generate one index per genome file.
I.e. 3 samples with different barcodes all use `hg19` but we only generate one `.mmi` file for `hg19`. This will make it significantly quicker and save a lot of storage.

Will look into the difference in output when using `chrSizes` and opposed to `UCSCchrSizes` - my understanding is ucsc one has different naming for chromosomes. But same deal as indexing - don't want to generate one `chrSizes` per sample if some samples are using the same reference genome.

**Comment by drpatelh** [comment]
Should now be fixed in https://github.com/nf-core/nanoseq/pull/26
